function Preloader(iface, context) {
  this.actual_image_no = 0;

  this.images_src = 
    [/*MARKER_START - NIE USUWAC K*RWA!!!*/
     'assets/img/attack_mark.png',
     'assets/img/bmenu/exit_active.png',
     'assets/img/bmenu/exit_inactive.png',
     'assets/img/bmenu/next_active.png',
     'assets/img/bmenu/next_inactive.png',
     'assets/img/bmenu/pauseoff.png',
     'assets/img/bmenu/pauseon.png',
     'assets/img/buttons/buyoff_LANG.png',
     'assets/img/buttons/buyon_LANG.png',
     'assets/img/conditionbar.png',
     'assets/img/cooldownbar2.png',
     'assets/img/creatures/czarnecka48.png',
     'assets/img/creatures/czarnecka98.png',
     'assets/img/creatures/demigor2.gif',
     'assets/img/creatures/ghul.png',
     'assets/img/creatures/gor.png',
     'assets/img/creatures/inzynier100.png',
     'assets/img/creatures/inzynier50.png',
     'assets/img/creatures/inzynier.gif',
     'assets/img/creatures/kokon100.png',
     'assets/img/creatures/komandoska.gif',
     'assets/img/creatures/korsarz_7.png',
     'assets/img/creatures/korsarz.png',
     'assets/img/creatures/krol_korsarzy.png',
     'assets/img/creatures/lidia48.png',
     'assets/img/creatures/lidia_duzy2.png',
     'assets/img/creatures/matrona.png',
     'assets/img/creatures/mutant_macka.png',
     'assets/img/creatures/mutant_pazur.png',
     'assets/img/creatures/mutant.png',
     'assets/img/creatures/olaf_duzy2.png',
     'assets/img/creatures/olaf_maly.png',
     'assets/img/creatures/pandora2.png',
     'assets/img/creatures/panel_lidia_duzy2.png',
     'assets/img/creatures/panel_olaf_duzy2.png',
     'assets/img/creatures/panel_szron_duzy2.png',
     'assets/img/creatures/pogromca_2.png',
     'assets/img/creatures/reptilian.png',
     'assets/img/creatures/reptoludz.png',
     'assets/img/creatures/rycerz.png',
     'assets/img/creatures/szczur.png',
     'assets/img/creatures/szron48.png',
     'assets/img/creatures/szron_duzy2.png',
     'assets/img/creatures/wojownik2.gif',
     'assets/img/creatures/zarazony.png',
     'assets/img/creatures/zbrojny_zielonych_smokow.png',
     'assets/img/creatures/zolnierka.png',
     'assets/img/creatures/zolnierz_broniacy.gif',
     'assets/img/creatures/zołnierz-ranny.gif',
     'assets/img/damagebar_roboczy.png',
     'assets/img/defeat.png',
     'assets/img/dot.png',
     'assets/img/email_field.png',
     'assets/img/filtr/armoron.png',
     'assets/img/filtr/armor.png',
     'assets/img/filtr/bialaon.png',
     'assets/img/filtr/biala.png',
     'assets/img/filtr/drugson.png',
     'assets/img/filtr/drugs.png',
     'assets/img/filtr/gunon.png',
     'assets/img/filtr/gun.png',
     'assets/img/fioletowa.png',
     'assets/img/fire_mini.png',
     'assets/img/fire.png',
     'assets/img/flash/0.png',
     'assets/img/flash/16.png',
     'assets/img/flash/1.png',
     'assets/img/flash/32.png',
     'assets/img/flash/4.png',
     'assets/img/flash/64.png',
     'assets/img/flash/8.png',
     'assets/img/flash/crit.png',
     'assets/img/flash/fail.png',
     'assets/img/flash/luck.png',
     'assets/img/flash/succ.png',
     'assets/img/healthbar.png',
     'assets/img/items/bron/podstawowa/bez_broni/rekawica_uderzeniowa.png',
     'assets/img/items/bron/podstawowa/bron_drzewcowa/dzida.png',
     'assets/img/items/bron/podstawowa/bron_drzewcowa/su_yari.png',
     'assets/img/items/bron/podstawowa/bron_drzewcowa/trojzab.png',
     'assets/img/items/bron/podstawowa/pistolety/falcon.png',
     'assets/img/items/bron/podstawowa/pistolety/nowak-3.png',
     'assets/img/items/bron/podstawowa/pistolety/pistolet_maszynowy_g-84.png',
     'assets/img/items/bron/podstawowa/pistolety/terkotka.png',
     'assets/img/items/bron/specjalna/komandos/luki/anglik.png',
     'assets/img/items/bron/specjalna/komandos/luki/luk_gorski.png',
     'assets/img/items/bron/specjalna/komandos/luki/luk_sportowy.png',
     'assets/img/items/bron/specjalna/komandos/ostrza_klujace/noz_wojskowy.png',
     'assets/img/items/bron/specjalna/komandos/ostrza_klujace/omega_v3.png',
     'assets/img/items/bron/specjalna/komandos/ostrza_klujace/yoroi-doshi.png',
     'assets/img/items/bron/specjalna/pogromca/kusze/artemida.png',
     'assets/img/items/bron/specjalna/pogromca/kusze/kusza_pistoletowa.png',
     'assets/img/items/bron/specjalna/pogromca/kusze/szpon_smoka.png',
     'assets/img/items/bron/specjalna/pogromca/miotacze/kwasu/bialostocki_odkazacz.png',
     'assets/img/items/bron/specjalna/pogromca/miotacze/kwasu/mini-miotacz_strumieniowy.png',
     'assets/img/items/bron/specjalna/pogromca/miotacze/ognia/palnik_bojowy.png',
     'assets/img/items/bron/specjalna/wojownik/mloty/miazdzyciel.png',
     'assets/img/items/bron/specjalna/wojownik/mloty/mlot_smieciowy.png',
     'assets/img/items/bron/specjalna/wojownik/mloty/mlot_wyburzeniowy.png',
     'assets/img/items/bron/specjalna/wojownik/ostrza_tnace/amelinium.png',
     'assets/img/items/bron/specjalna/wojownik/ostrza_tnace/kordelas.png',
     'assets/img/items/bron/specjalna/wojownik/ostrza_tnace/smoczy_pazur.png',
     'assets/img/items/bron/specjalna/zolnierz/karabiny/eksterminator.png',
     'assets/img/items/bron/specjalna/zolnierz/karabiny/kapiszon.png',
     'assets/img/items/bron/specjalna/zolnierz/karabiny_maszynowe/mwg_26.png',
     'assets/img/items/bron/specjalna/zolnierz/karabiny_maszynowe/tytan_2.png',
     'assets/img/items/bron/specjalna/zolnierz/karabiny_maszynowe/tytan3alfa.png',
     'assets/img/items/bron/specjalna/zolnierz/karabiny/plujka.png',
     'assets/img/items/pancerz/ciezkie/napiersnik.png',
     'assets/img/items/pancerz/ciezkie/plytowa.png',
     'assets/img/items/pancerz/lekkie/kirys.png',
     'assets/img/items/pancerz/lekkie/plaszcz.png',
     'assets/img/items/pancerz/srednie/kamizelka_wojskowa.png',
     'assets/img/items/pancerz/srednie/obronca2.png',
     'assets/img/items/uzywki/medykamenty/uzdrawiacz2.png',
     'assets/img/items/uzywki/medykamenty/uzdrawiacz.png',
     'assets/img/items/uzywki/specyfiki/dopalacz2.png',
     'assets/img/items/uzywki/specyfiki/dopalacz.png',
     'assets/img/items/uzywki/specyfiki/puma2.png',
     'assets/img/items/uzywki/specyfiki/puma.png',
     'assets/img/jezyk/pl_off.png',
     'assets/img/jezyk/pl_on.png',
     'assets/img/jezyk/uk_off.png',
     'assets/img/jezyk/uk_on.png',
     'assets/img/koncowy.png',
     'assets/img/level.png',
     'assets/img/levels/gdanska_fabryka.png',
     'assets/img/levels/gdanskie_wybrzeze.png',
     'assets/img/levels/gdynska_plaza.png',
     'assets/img/levels/krakowskie_metro.png',
     'assets/img/levels/laboratorium.png',
     'assets/img/levels/level_0_foreground.png',
     'assets/img/levels/metro_plac_wilsona.png',
     'assets/img/levels/metro_swietokrzyska.png',
     'assets/img/levels/minski_las2.png',
     'assets/img/levels/minski_las.png',
     'assets/img/levels/okolice_krakowa.png',
     'assets/img/levels/replay_level_0_foreground.png',
     'assets/img/levels/sopocka_ulica.png',
     'assets/img/levels/speech_0_1.png',
     'assets/img/levels/speech_0_2.png',
     'assets/img/levels/speech_0_3.png',
     'assets/img/levels/stare_miasto.png',
     'assets/img/levels/ulice_krakowa.png',
     'assets/img/levels/warszawska_ulica.png',
     'assets/img/menu/creditsoff_LANG.png',
     'assets/img/menu/mapoff_LANG.png',
     'assets/img/menu/mapon_LANG.png',
     'assets/img/menu/optionsoff_LANG.png',
     'assets/img/menu/optionson_LANG.png',
     'assets/img/menu/shopoff_LANG.png',
     'assets/img/menu/shopon_LANG.png',
     'assets/img/menu/support_LANG.png',
     'assets/img/miecze.png',
     'assets/img/move_mark.png',
     'assets/img/music_off.png',
     'assets/img/music_on.png',
     'assets/img/niezaznaczenie2.png',
     'assets/img/panele/opcjepaper.png',
     'assets/img/panele/panelboczny.png',
     'assets/img/panele/panel_glowny2.png',
     'assets/img/panele/panelsklep.png',
     'assets/img/panele/poland.png',
     'assets/img/password_field.png',
     'assets/img/pause_mask.png',
     'assets/img/+.png',
     'assets/img/poison_mini.png',
     'assets/img/poison.png',
     'assets/img/preloader/background.png',
     'assets/img/preloader/bar_background.png',
     'assets/img/preloader/bar_foreground.png',
     'assets/img/skillbar.png',
     'assets/img/skills/lidia1.png',
     'assets/img/skills/lidia2.png',
     'assets/img/skills/olaf1.png',
     'assets/img/skills/olaf2.png',
     'assets/img/skills/szron1.png',
     'assets/img/skills/szron2.png',
     'assets/img/sound_off.png',
     'assets/img/sound_on.png',
     'assets/img/startoff.png',
     'assets/img/starton.png',
     'assets/img/story/00/LANG/d/begining/1/10.jpg',
     'assets/img/story/00/LANG/d/begining/1/11.jpg',
     'assets/img/story/00/LANG/d/begining/1/12.jpg',
     'assets/img/story/00/LANG/d/begining/1/13.jpg',
     'assets/img/story/00/LANG/d/begining/1/14.jpg',
     'assets/img/story/00/LANG/d/begining/1/15.jpg',
     'assets/img/story/00/LANG/d/begining/1/16.jpg',
     'assets/img/story/00/LANG/d/begining/1/17.jpg',
     'assets/img/story/00/LANG/d/begining/1/18.jpg',
     'assets/img/story/00/LANG/d/begining/1/19.jpg',
     'assets/img/story/00/LANG/d/begining/1/1.jpg',
     'assets/img/story/00/LANG/d/begining/1/20.jpg',
     'assets/img/story/00/LANG/d/begining/1/21.jpg',
     'assets/img/story/00/LANG/d/begining/1/22.jpg',
     'assets/img/story/00/LANG/d/begining/1/2.jpg',
     'assets/img/story/00/LANG/d/begining/1/3.jpg',
     'assets/img/story/00/LANG/d/begining/1/4.jpg',
     'assets/img/story/00/LANG/d/begining/1/5.jpg',
     'assets/img/story/00/LANG/d/begining/1/6.jpg',
     'assets/img/story/00/LANG/d/begining/1/7.jpg',
     'assets/img/story/00/LANG/d/begining/1/8.jpg',
     'assets/img/story/00/LANG/d/begining/1/9.jpg',
     'assets/img/story/00/LANG/d/begining/2/1.jpg',
     'assets/img/story/00/LANG/d/begining/2/2.jpg',
     'assets/img/story/00/LANG/d/begining/2/3.jpg',
     'assets/img/story/00/LANG/d/end/1/1.jpg',
     'assets/img/story/00/LANG/d/end/1/2.jpg',
     'assets/img/story/00/LANG/d/end/1/3.jpg',
     'assets/img/story/00/LANG/d/end/1/4.jpg',
     'assets/img/story/00/LANG/d/end/1/5.jpg',
     'assets/img/story/00/LANG/d/end/1/6.jpg',
     'assets/img/story/00/LANG/d/end/2/1.jpg',
     'assets/img/story/00/LANG/t/3.jpg',
     'assets/img/story/00/LANG/t/5.jpg',
     'assets/img/story/00/LANG/t/7.jpg',
     'assets/img/story/00/LANG/t/8.jpg',
     'assets/img/story/01/LANG/d/begining/1/10.jpg',
     'assets/img/story/01/LANG/d/begining/1/11.jpg',
     'assets/img/story/01/LANG/d/begining/1/12.jpg',
     'assets/img/story/01/LANG/d/begining/1/13.jpg',
     'assets/img/story/01/LANG/d/begining/1/14.jpg',
     'assets/img/story/01/LANG/d/begining/1/15.jpg',
     'assets/img/story/01/LANG/d/begining/1/16.jpg',
     'assets/img/story/01/LANG/d/begining/1/17.jpg',
     'assets/img/story/01/LANG/d/begining/1/18.jpg',
     'assets/img/story/01/LANG/d/begining/1/19.jpg',
     'assets/img/story/01/LANG/d/begining/1/1.jpg',
     'assets/img/story/01/LANG/d/begining/1/20.jpg',
     'assets/img/story/01/LANG/d/begining/1/21.jpg',
     'assets/img/story/01/LANG/d/begining/1/22.jpg',
     'assets/img/story/01/LANG/d/begining/1/23.jpg',
     'assets/img/story/01/LANG/d/begining/1/24.jpg',
     'assets/img/story/01/LANG/d/begining/1/25.jpg',
     'assets/img/story/01/LANG/d/begining/1/26.jpg',
     'assets/img/story/01/LANG/d/begining/1/27.jpg',
     'assets/img/story/01/LANG/d/begining/1/28.jpg',
     'assets/img/story/01/LANG/d/begining/1/29.jpg',
     'assets/img/story/01/LANG/d/begining/1/2.jpg',
     'assets/img/story/01/LANG/d/begining/1/30.jpg',
     'assets/img/story/01/LANG/d/begining/1/31.jpg',
     'assets/img/story/01/LANG/d/begining/1/32.jpg',
     'assets/img/story/01/LANG/d/begining/1/33.jpg',
     'assets/img/story/01/LANG/d/begining/1/3.jpg',
     'assets/img/story/01/LANG/d/begining/1/4.jpg',
     'assets/img/story/01/LANG/d/begining/1/5.jpg',
     'assets/img/story/01/LANG/d/begining/1/6.jpg',
     'assets/img/story/01/LANG/d/begining/1/7.jpg',
     'assets/img/story/01/LANG/d/begining/1/8.jpg',
     'assets/img/story/01/LANG/d/begining/1/9.jpg',
     'assets/img/story/01/LANG/d/begining/2/1.jpg',
     'assets/img/story/01/LANG/d/begining/2/2.jpg',
     'assets/img/story/01/LANG/d/begining/2/3.jpg',
     'assets/img/story/01/LANG/d/begining/2/4.jpg',
     'assets/img/story/01/LANG/d/end/1/10.jpg',
     'assets/img/story/01/LANG/d/end/1/1.jpg',
     'assets/img/story/01/LANG/d/end/1/2.jpg',
     'assets/img/story/01/LANG/d/end/1/3.jpg',
     'assets/img/story/01/LANG/d/end/1/4.jpg',
     'assets/img/story/01/LANG/d/end/1/5.jpg',
     'assets/img/story/01/LANG/d/end/1/6.jpg',
     'assets/img/story/01/LANG/d/end/1/7.jpg',
     'assets/img/story/01/LANG/d/end/1/8.jpg',
     'assets/img/story/01/LANG/d/end/1/9.jpg',
     'assets/img/story/01/LANG/d/end/2/1.jpg',
     'assets/img/story/02/LANG/d/begining/1/1.jpg',
     'assets/img/story/02/LANG/d/begining/1/2.jpg',
     'assets/img/story/02/LANG/d/begining/1/3.jpg',
     'assets/img/story/02/LANG/d/begining/1/4.jpg',
     'assets/img/story/02/LANG/d/begining/1/5.jpg',
     'assets/img/story/02/LANG/d/begining/2/1.jpg',
     'assets/img/story/02/LANG/d/begining/2/2.jpg',
     'assets/img/story/02/LANG/d/end/1/1.jpg',
     'assets/img/story/02/LANG/d/end/1/2.jpg',
     'assets/img/story/02/LANG/d/end/1/3.jpg',
     'assets/img/story/02/LANG/d/end/1/4.jpg',
     'assets/img/story/02/LANG/d/end/1/5.jpg',
     'assets/img/story/02/LANG/d/end/1/6.jpg',
     'assets/img/story/02/LANG/d/end/1/7.jpg',
     'assets/img/story/02/LANG/d/end/2/1.jpg',
     'assets/img/story/02/LANG/d/end/2/2.jpg',
     'assets/img/story/02/LANG/t/1.jpg',
     'assets/img/story/03/LANG/d/begining/1/10.jpg',
     'assets/img/story/03/LANG/d/begining/1/11.jpg',
     'assets/img/story/03/LANG/d/begining/1/12.jpg',
     'assets/img/story/03/LANG/d/begining/1/13.jpg',
     'assets/img/story/03/LANG/d/begining/1/14.jpg',
     'assets/img/story/03/LANG/d/begining/1/15.jpg',
     'assets/img/story/03/LANG/d/begining/1/16.jpg',
     'assets/img/story/03/LANG/d/begining/1/17.jpg',
     'assets/img/story/03/LANG/d/begining/1/18.jpg',
     'assets/img/story/03/LANG/d/begining/1/1.jpg',
     'assets/img/story/03/LANG/d/begining/1/2.jpg',
     'assets/img/story/03/LANG/d/begining/1/3.jpg',
     'assets/img/story/03/LANG/d/begining/1/4.jpg',
     'assets/img/story/03/LANG/d/begining/1/5.jpg',
     'assets/img/story/03/LANG/d/begining/1/6.jpg',
     'assets/img/story/03/LANG/d/begining/1/7.jpg',
     'assets/img/story/03/LANG/d/begining/1/8.jpg',
     'assets/img/story/03/LANG/d/begining/1/9.jpg',
     'assets/img/story/03/LANG/d/end/1/10.jpg',
     'assets/img/story/03/LANG/d/end/1/11.jpg',
     'assets/img/story/03/LANG/d/end/1/12.jpg',
     'assets/img/story/03/LANG/d/end/1/13.jpg',
     'assets/img/story/03/LANG/d/end/1/14.jpg',
     'assets/img/story/03/LANG/d/end/1/15.jpg',
     'assets/img/story/03/LANG/d/end/1/16.jpg',
     'assets/img/story/03/LANG/d/end/1/17.jpg',
     'assets/img/story/03/LANG/d/end/1/18.jpg',
     'assets/img/story/03/LANG/d/end/1/1.jpg',
     'assets/img/story/03/LANG/d/end/1/2.jpg',
     'assets/img/story/03/LANG/d/end/1/3.jpg',
     'assets/img/story/03/LANG/d/end/1/4.jpg',
     'assets/img/story/03/LANG/d/end/1/5.jpg',
     'assets/img/story/03/LANG/d/end/1/6.jpg',
     'assets/img/story/03/LANG/d/end/1/7.jpg',
     'assets/img/story/03/LANG/d/end/1/8.jpg',
     'assets/img/story/03/LANG/d/end/1/9.jpg',
     'assets/img/story/03/LANG/d/mid/1.jpg',
     'assets/img/story/03/LANG/d/mid/2.jpg',
     'assets/img/story/03/LANG/d/mid/3.jpg',
     'assets/img/story/dialogues/ai_szron_next_exit.png',
     'assets/img/story/dialogues/kos_lidia_next_exit.png',
     'assets/img/story/dialogues/kos_szron_next_exit.png',
     'assets/img/story/dialogues/kruk_szron_next_exit.png',
     'assets/img/story/dialogues/lidia_kos_next_exit.png',
     'assets/img/story/dialogues/lidia_olaf_next_exit.png',
     'assets/img/story/dialogues/lidia_szron_exit.png',
     'assets/img/story/dialogues/lidia_szron_next_exit.png',
     'assets/img/story/dialogues/olaf_kruk_next_exit.png',
     'assets/img/story/dialogues/olaf_lidia_exit.png',
     'assets/img/story/dialogues/olaf_lidia_next_exit.png',
     'assets/img/story/dialogues/olaf_szron_exit.png',
     'assets/img/story/dialogues/olaf_szron_next_exit.png',
     'assets/img/story/dialogues/piotrkowski_next_exit.png',
     'assets/img/story/dialogues/szron_ai_exit.png',
     'assets/img/story/dialogues/szron_ai_next_exit.png',
     'assets/img/story/dialogues/szron_exit.png',
     'assets/img/story/dialogues/szron_kos_exit.png',
     'assets/img/story/dialogues/szron_kos_next_exit.png',
     'assets/img/story/dialogues/szron_kruk_exit.png',
     'assets/img/story/dialogues/szron_kruk_next_exit.png',
     'assets/img/story/dialogues/szron_lidia_exit.png',
     'assets/img/story/dialogues/szron_lidia_next_exit.png',
     'assets/img/story/dialogues/szron_next_exit.png',
     'assets/img/story/dialogues/szron_olaf_exit.png',
     'assets/img/story/dialogues/szron_olaf_next_exit.png',
     'assets/img/story/tips/misja2p.jpg',
     'assets/img/story/tips/misja3p.jpg',
     'assets/img/story/tips/misja4p.jpg',
     'assets/img/story/tips/tip10_LANG.jpg',
     'assets/img/story/tips/tip11_LANG.jpg',
     'assets/img/story/tips/tip12_LANG.jpg',
     'assets/img/story/tips/tip1_LANG.jpg',
     'assets/img/story/tips/tip2_LANG.jpg',
     'assets/img/story/tips/tip3_LANG.jpg',
     'assets/img/story/tips/tip4_LANG.jpg',
     'assets/img/story/tips/tip5_LANG.jpg',
     'assets/img/story/tips/tip6_LANG.jpg',
     'assets/img/story/tips/tip7_LANG.jpg',
     'assets/img/story/tips/tip8_LANG.jpg',
     'assets/img/story/tips/tip9_LANG.jpg',
     'assets/img/story/tips/tipmapa_LANG.jpg',
     'assets/img/story/tips/tipogolny_LANG.jpg',
     'assets/img/story/tips/tipopcje_LANG.jpg',
     'assets/img/story/tips/tipsklep_LANG.jpg',
     'assets/img/strzala.png',
     'assets/img/strzalki/arrow_down.png',
     'assets/img/strzalki/arrow_left.png',
     'assets/img/strzalki/arrow_right.png',
     'assets/img/strzalki/arrow_up.png',
     'assets/img/tarczka.png',
     'assets/img/victory.png',
     'assets/img/zaznaczenie2.png',
     'assets/img/zielona.png',
     'assets/img/znajdzki/ammodrop.png',
     'assets/img/znajdzki/biceps.png',
     'assets/img/znajdzki/biegnacy.png',
     'assets/img/znajdzki/eksplozja.png',
     'assets/img/znajdzki/healthdrop.png',
     'assets/img/znajdzki/snieg.png',
     'assets/img/znajdzki/tarcza.png',
     'assets/img/znajdzki/violkidrop.png',
     'assets/img/znak_zapytania.png',
    /*MARKER_END - NIE USUWAC K*RWA!!!*/];

  this.iface = iface;
  this.context = context;

  this.config = global_config.preloader; 
  this.bar_background = Image.from_src(this.config.bar_background);
  this.bar_foreground = Image.from_src(this.config.bar_foreground);
  this.loader_background = Image.from_src(this.config.background);
  this.bar_width = this.config.bar_width;
  this.bar_height = this.config.bar_height;
}

Preloader.prototype.loaded = function() {
  this.iface.start();
};

Preloader.prototype.preload = function() {
  this.load_next_image();
};

Preloader.prototype.load_next_image = function() {
  this.draw();
  if (this.actual_image_no >= this.images_src.length) {
    this.loaded();
  } else {
    var src = this.images_src[this.actual_image_no];
    if (src == this.config.bar_background || src == this.config.bar_foreground || src == this.config.background) {
      debug.debug("omijam "+src);
      this.actual_image_no++;
      this.load_next_image();
    } else {
      // debug.debug("Laduje "+src);
      Image.from_src(src, 
        function(preloader) {
          return function() {
            preloader.actual_image_no++;
            preloader.load_next_image();
          };
        }(this),
        function(preloader) {
          return function() {
            debug.warn("Nie udalo sie wczytac obrazka: " + preloader.images_src[preloader.actual_image_no]);
            preloader.actual_image_no++;
            preloader.load_next_image();
          };
        }(this)
        );
    }
  }
};

Preloader.prototype.draw = function() {
  try {
    this.context.drawImage(this.loader_background, 0, 0);
    this.context.drawImage(this.bar_background, this.config.bar_x, this.config.bar_y);
    var width = Math.ceil(this.bar_width * this.actual_image_no / this.images_src.length);
    this.context.drawImage(this.bar_foreground, 0, 0, width, this.config.bar_height, this.config.bar_x, this.config.bar_y, width, this.config.bar_height);
  } catch (e) {
    debug.warn("Wyjatek z preloadera", e);
  }
};


